### ISSUE TITLE
Human based SRL questions

### ISSUE THREAD

**Issue by chaitanyamalaviya** [phueb/CHILDES-SRL#6]
Hi,

Thank you for hosting the childes-srl data. I had a couple questions that I wanted to ask about the human srl dataset:

1) What is the difference between `human-based-2008_srl.txt` and `human-based-2018_srl.txt`?
2) Do you know where I might be able to find the sense annotations for the predicates in each utterance? It seems like the senses are just labeled as `sense="write.XX"` in the original data.

Thanks!
Chaitanya

**Comment by phueb** [comment]
Chaitanya,

The difference is that the 2018 data includes the 2008 data but also 
more data that includes adjectives and prepositions as predicates. 
However, I noticed that there are a lot of errors in the 2018 data, 
which are not in the 2008 data.

The sense annotation was never included in this data, as far as I know. 
If you want to make sure, please ask Cynthia Fisher who was responsible 
for data gathering (I am just the one who made it available publicly). 
Her info : https://psychology.illinois.edu/directory/profile/clfishe

Best,

Philip

**Comment by chaitanyamalaviya** [comment]
Thanks Philip, that's helpful!

**Comment by chaitanyamalaviya** [comment]
Hi Philip,

I had another question. To generate `human-based-2008_srl.txt` using the `make_srl_training_data_from_human.py` script, did you use the XML files from [here](https://cogcomp.seas.upenn.edu/page/resource_view/24)? 
Using this data, I seem to be getting 17,472 lines in the output file, while the same file in the repo has 14,771 lines. I was wondering what the difference might be due to. Thanks!

**Comment by phueb** [comment]
There was a small problem in `make_srl_training_data_from_human.py`: It is supposed to skip utterances produced by children, but it was not implemented correctly. I fixed this, and tested the output. Now, using the 2008 data (yes, that is the correct URL) produces a file that has 14,771 lines.  Thank you for bringing this to my attention.

**Comment by chaitanyamalaviya** [comment]
Great, thanks again!
